In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,10,(4,4))

In [3]:
arr

array([[4, 3, 9, 7],
       [6, 5, 1, 2],
       [3, 2, 5, 7],
       [3, 5, 5, 7]])

In [5]:
arr.reshape((2,8))

array([[4, 3, 9, 7, 6, 5, 1, 2],
       [3, 2, 5, 7, 3, 5, 5, 7]])

In [12]:
arr.T #Transpose og given array

array([[4, 6, 3, 3],
       [3, 5, 2, 5],
       [9, 1, 5, 5],
       [7, 2, 7, 7]])

In [15]:
arr

array([[4, 3, 9, 7],
       [6, 5, 1, 2],
       [3, 2, 5, 7],
       [3, 5, 5, 7]])

In [17]:
arr.flatten()  #Creates 1d array from multi dimension given array

array([4, 3, 9, 7, 6, 5, 1, 2, 3, 2, 5, 7, 3, 5, 5, 7])

In [21]:
a=np.expand_dims(arr,axis=1)

In [22]:
a

array([[[4, 3, 9, 7]],

       [[6, 5, 1, 2]],

       [[3, 2, 5, 7]],

       [[3, 5, 5, 7]]])

In [23]:
a.ndim

3

In [24]:
data=np.array([[1],[2],[3]]),

In [25]:
data

(array([[1],
        [2],
        [3]]),)

In [27]:
np.squeeze(data)

array([1, 2, 3])

In [30]:
data

(array([[1],
        [2],
        [3]]),)

In [29]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [33]:
np.roll(data,2)

array([[[2],
        [3],
        [1]]])

In [37]:
np.roll(data,3)

array([[[1],
        [2],
        [3]]])

In [39]:
np.roll(data,4)

array([[[3],
        [1],
        [2]]])

In [40]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [41]:
#Numpy - Binary Operators

In [44]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [45]:
arr1

array([[6, 1, 9, 8],
       [5, 7, 2, 5],
       [6, 4, 8, 9]])

In [46]:
arr2

array([[6, 5, 7, 3],
       [9, 1, 1, 3],
       [3, 9, 4, 6]])

In [47]:
arr1+arr2

array([[12,  6, 16, 11],
       [14,  8,  3,  8],
       [ 9, 13, 12, 15]])

In [48]:
arr1*arr2

array([[36,  5, 63, 24],
       [45,  7,  2, 15],
       [18, 36, 32, 54]])

In [49]:
arr1-arr2

array([[ 0, -4,  2,  5],
       [-4,  6,  1,  2],
       [ 3, -5,  4,  3]])

In [50]:
arr1/arr2

array([[1.        , 0.2       , 1.28571429, 2.66666667],
       [0.55555556, 7.        , 2.        , 1.66666667],
       [2.        , 0.44444444, 2.        , 1.5       ]])

In [51]:
arr1

array([[6, 1, 9, 8],
       [5, 7, 2, 5],
       [6, 4, 8, 9]])

In [52]:
arr2

array([[6, 5, 7, 3],
       [9, 1, 1, 3],
       [3, 9, 4, 6]])

In [53]:
arr1-2

array([[ 4, -1,  7,  6],
       [ 3,  5,  0,  3],
       [ 4,  2,  6,  7]])

In [54]:
#This all operations on array happend index wise

In [55]:
arr1**arr2

array([[  46656,       1, 4782969,     512],
       [1953125,       7,       2,     125],
       [    216,  262144,    4096,  531441]])

In [57]:
arr1

array([[6, 1, 9, 8],
       [5, 7, 2, 5],
       [6, 4, 8, 9]])

In [59]:
-arr1

array([[-6, -1, -9, -8],
       [-5, -7, -2, -5],
       [-6, -4, -8, -9]])

In [60]:
arr1>arr2

array([[False, False,  True,  True],
       [False,  True,  True,  True],
       [ True, False,  True,  True]])

In [61]:
#Numpy - String Functions

In [62]:
arr = np.array(["sudh","kumar"])

In [63]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [68]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [69]:
np.char.lower(arr)

array(['sudh', 'kumar'], dtype='<U5')

In [73]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [75]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [77]:
#Numpy - Mathematical Functions

In [80]:
arr1

array([[6, 1, 9, 8],
       [5, 7, 2, 5],
       [6, 4, 8, 9]])

In [81]:
np.sin(arr1)

array([[-0.2794155 ,  0.84147098,  0.41211849,  0.98935825],
       [-0.95892427,  0.6569866 ,  0.90929743, -0.95892427],
       [-0.2794155 , -0.7568025 ,  0.98935825,  0.41211849]])

In [82]:
np.tan(arr1)

array([[-0.29100619,  1.55740772, -0.45231566, -6.79971146],
       [-3.38051501,  0.87144798, -2.18503986, -3.38051501],
       [-0.29100619,  1.15782128, -6.79971146, -0.45231566]])

In [83]:
np.mean(arr1)

5.833333333333333

In [84]:
np.std(arr1)

2.4776781245530843

In [85]:
arr1

array([[6, 1, 9, 8],
       [5, 7, 2, 5],
       [6, 4, 8, 9]])

In [86]:
np.max(arr1)

9

In [88]:
np.min(arr1)

1

In [89]:
np.exp(arr1)

array([[4.03428793e+02, 2.71828183e+00, 8.10308393e+03, 2.98095799e+03],
       [1.48413159e+02, 1.09663316e+03, 7.38905610e+00, 1.48413159e+02],
       [4.03428793e+02, 5.45981500e+01, 2.98095799e+03, 8.10308393e+03]])

In [92]:
np.median(arr1)

6.0

In [94]:
arr1

array([[6, 1, 9, 8],
       [5, 7, 2, 5],
       [6, 4, 8, 9]])

In [93]:
np.power(arr1,3)

array([[216,   1, 729, 512],
       [125, 343,   8, 125],
       [216,  64, 512, 729]])

In [95]:
np.std(arr1)

2.4776781245530843

In [96]:
np.var(arr1)

6.138888888888889

In [97]:
#Numpy - Arithmetic Operations

In [98]:
arr1

array([[6, 1, 9, 8],
       [5, 7, 2, 5],
       [6, 4, 8, 9]])

In [99]:
arr2

array([[6, 5, 7, 3],
       [9, 1, 1, 3],
       [3, 9, 4, 6]])

In [100]:
arr1-arr2

array([[ 0, -4,  2,  5],
       [-4,  6,  1,  2],
       [ 3, -5,  4,  3]])

In [102]:
np.subtract(arr1,arr2)

array([[ 0, -4,  2,  5],
       [-4,  6,  1,  2],
       [ 3, -5,  4,  3]])

In [103]:
arr1*arr2

array([[36,  5, 63, 24],
       [45,  7,  2, 15],
       [18, 36, 32, 54]])

In [104]:
np.multiply(arr1,arr2)

array([[36,  5, 63, 24],
       [45,  7,  2, 15],
       [18, 36, 32, 54]])

In [105]:
np.sqrt(arr1)

array([[2.44948974, 1.        , 3.        , 2.82842712],
       [2.23606798, 2.64575131, 1.41421356, 2.23606798],
       [2.44948974, 2.        , 2.82842712, 3.        ]])

In [106]:
#Numpy - Statistical Functions

In [107]:
arr1

array([[6, 1, 9, 8],
       [5, 7, 2, 5],
       [6, 4, 8, 9]])

In [108]:
np.mean(arr1)

5.833333333333333

In [109]:
np.std(arr1)

2.4776781245530843

In [111]:
np.mean(arr1-arr2)

1.0833333333333333

In [113]:
np.median(arr1)

6.0

In [114]:
np.var(arr1)

6.138888888888889

In [115]:
#Sort,Search and Count Functions

In [116]:
import numpy as np

In [121]:
arr=np.array([7,2,9,8,4,6])

In [122]:
arr

array([7, 2, 9, 8, 4, 6])

In [123]:
np.sort(arr)

array([2, 4, 6, 7, 8, 9])

In [132]:
np.searchsorted(arr,4) #Tells where i can put my data 4 in sorted arr that is i can put 4 at index positon of 2

2

In [131]:
arr

array([7, 2, 9, 8, 4, 6])

In [134]:
np.searchsorted(arr,10)

6

In [135]:
np.searchsorted(arr,1)

0

In [136]:
arr=np.array([0,4,5,1,2,4,4,5,5,6,9,7,5,1,2,4,5,1,2])

In [137]:
arr

array([0, 4, 5, 1, 2, 4, 4, 5, 5, 6, 9, 7, 5, 1, 2, 4, 5, 1, 2])

In [138]:
np.count_nonzero(arr)

18

In [144]:
np.where(arr>2) #Gives array index where i have data>0

(array([ 1,  2,  5,  6,  7,  8,  9, 10, 11, 12, 15, 16]),)

In [147]:
arr

array([0, 4, 5, 1, 2, 4, 4, 5, 5, 6, 9, 7, 5, 1, 2, 4, 5, 1, 2])

In [146]:
np.extract(arr>5,arr)

array([6, 9, 7])

In [148]:
arr[arr>5]

array([6, 9, 7])

In [149]:
#Numpy - Byte Swapping

In [150]:
arr

array([0, 4, 5, 1, 2, 4, 4, 5, 5, 6, 9, 7, 5, 1, 2, 4, 5, 1, 2])

In [152]:
arr.byteswap() #Gives how internally that index data is stored in system

array([                 0, 288230376151711744, 360287970189639680,
        72057594037927936, 144115188075855872, 288230376151711744,
       288230376151711744, 360287970189639680, 360287970189639680,
       432345564227567616, 648518346341351424, 504403158265495552,
       360287970189639680,  72057594037927936, 144115188075855872,
       288230376151711744, 360287970189639680,  72057594037927936,
       144115188075855872])

In [153]:
#Numpy - Copies and Views

In [154]:
arr

array([0, 4, 5, 1, 2, 4, 4, 5, 5, 6, 9, 7, 5, 1, 2, 4, 5, 1, 2])

In [155]:
a=np.copy(arr) #Deep copy

In [156]:
a

array([0, 4, 5, 1, 2, 4, 4, 5, 5, 6, 9, 7, 5, 1, 2, 4, 5, 1, 2])

In [157]:
arr

array([0, 4, 5, 1, 2, 4, 4, 5, 5, 6, 9, 7, 5, 1, 2, 4, 5, 1, 2])

In [160]:
b=arr.view()

In [161]:
b

array([0, 4, 5, 1, 2, 4, 4, 5, 5, 6, 9, 7, 5, 1, 2, 4, 5, 1, 2])

In [162]:
b[0]=12

In [163]:
b

array([12,  4,  5,  1,  2,  4,  4,  5,  5,  6,  9,  7,  5,  1,  2,  4,  5,
        1,  2])

In [164]:
arr

array([12,  4,  5,  1,  2,  4,  4,  5,  5,  6,  9,  7,  5,  1,  2,  4,  5,
        1,  2])

In [166]:
#Therefore view creates shallow copy
#So change  in any one of both will change other as both point to same memory location

In [167]:
#Numpy - Matrix Library

In [168]:
import numpy.matlib as nm

In [169]:
#This is matlib is matrix library in numpy

In [170]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [171]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [172]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [174]:
nm.eye(4) #Identity square matrix 

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [175]:
#Numpy - Linear Algebra

In [179]:
arr1 = np.random.randint(2,8,(4,4))

In [180]:
arr2 = np.random.randint(2,8,(4,4))

In [181]:
arr1

array([[3, 3, 7, 6],
       [4, 3, 7, 3],
       [4, 4, 7, 4],
       [6, 4, 6, 7]])

In [182]:
arr2

array([[6, 6, 2, 4],
       [4, 6, 2, 7],
       [4, 2, 2, 4],
       [4, 3, 2, 4]])

In [185]:
arr1@arr2 #Does matrix multiplication on both array

array([[ 82,  68,  38,  85],
       [ 76,  65,  34,  77],
       [ 84,  74,  38,  88],
       [104,  93,  46, 104]])

In [190]:
np.dot(arr1,arr2) #Same does matrix multiplication in linear algebra

array([[ 82,  68,  38,  85],
       [ 76,  65,  34,  77],
       [ 84,  74,  38,  88],
       [104,  93,  46, 104]])