In [164]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5])

In [4]:
type(l)

list

In [5]:
type(np.array(l))

numpy.ndarray

In [6]:
#That is n dimensional array

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
#Both function creates array from list. np.array(l) and np.asarray(l)

In [9]:
arr1=np.array(l)

In [10]:
arr2=np.asarray(l)

In [11]:
arr1

array([1, 2, 3, 4, 5])

In [12]:
arr2

array([1, 2, 3, 4, 5])

In [13]:
type(arr1)

numpy.ndarray

In [14]:
type(arr2)

numpy.ndarray

In [15]:
np.array([[1,2,3],[2,3,4]])

array([[1, 2, 3],
       [2, 3, 4]])

In [17]:
type(np.array([[1,2,3],[2,3,4]]))

numpy.ndarray

In [18]:
arr2=np.array([[1,2,3],[2,3,4]])

In [19]:
arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [22]:
arr1.ndim #1D ARRAY

1

In [23]:
arr2.ndim #2D ARRAY

2

In [27]:
mat1=np.matrix(arr1)

In [28]:
mat2=np.matrix(arr2)

In [29]:
mat1

matrix([[1, 2, 3, 4, 5]])

In [30]:
mat2

matrix([[1, 2, 3],
        [2, 3, 4]])

In [33]:
arr3=np.array([[1,2,3],[2,3,4],[4,5,6]])

In [34]:
mat3=np.matrix(arr3)

In [35]:
mat3

matrix([[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]])

In [37]:
mat1.ndim

2

In [38]:
mat2.ndim

2

In [39]:
mat3.ndim

2

In [40]:
#So matrix in numpy is always two dimensional or 2d

In [41]:
l=[1,2,3,4,5]

In [42]:
arr=np.array(l)

In [43]:
arr

array([1, 2, 3, 4, 5])

In [50]:
a=arr #Shallow copy

In [45]:
a

array([1, 2, 3, 4, 5])

In [46]:
arr[0]=2

In [47]:
arr

array([2, 2, 3, 4, 5])

In [48]:
a

array([2, 2, 3, 4, 5])

In [49]:
#Therefore a is shallow copy of array because both a and arr point to same location

In [51]:
b=np.copy(arr)

In [53]:
arr

array([2, 2, 3, 4, 5])

In [54]:
b

array([2, 2, 3, 4, 5])

In [55]:
arr[2]=10

In [56]:
arr

array([ 2,  2, 10,  4,  5])

In [57]:
b

array([2, 2, 3, 4, 5])

In [58]:
#Therefore b and arr are deep copy of each other because both have different memory location b and arr

In [3]:
np.fromfunction(lambda i,j:i==j,(3,3))  #GENERATE ARRAY ON OUR CONDITION

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [5]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [10]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [14]:
np.fromfunction(i*i for i in range(5),(3,3))

SyntaxError: Generator expression must be parenthesized (1048784703.py, line 1)

In [7]:
a= tuple(i*i for i in range(5))

In [8]:
a

(0, 1, 4, 9, 16)

In [9]:
np.fromiter(a,float)

array([ 0.,  1.,  4.,  9., 16.])

In [11]:
b=(i**2 for i in range(1,10,2))

In [13]:
np.fromiter(b,int)

array([ 1,  9, 25, 49, 81])

In [18]:
np.fromstring('23 45 67',sep = ' ')

array([23., 45., 67.])

In [19]:
np.fromstring('23,45,67',sep = ',')

array([23., 45., 67.])

In [24]:
arr=np.array([100,2,3,4,5])

In [25]:
arr1=np.array([[1,2,3],[2,3,4]])

In [26]:
arr

array([100,   2,   3,   4,   5])

In [27]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [28]:
arr.ndim

1

In [29]:
arr1.ndim

2

In [30]:
arr.size

5

In [32]:
arr1.size

6

In [33]:
#Size gives total elements in array

In [38]:
arr.shape #5 columns

(5,)

In [39]:
arr1.shape #2 rows 3 columns

(2, 3)

In [40]:
arr.dtype

dtype('int64')

In [41]:
arr1.dtype

dtype('int64')

In [42]:
range(5)

range(0, 5)

In [43]:
list(range(5))

[0, 1, 2, 3, 4]

In [44]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [46]:
#That is range function works on only integer positional argument

In [48]:
np.arange(0.4,10.4) #But arange function in numpy can even use float as positional argument that is it is extended version of range

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [49]:
np.arange(0.4,10.4,2)

array([0.4, 2.4, 4.4, 6.4, 8.4])

In [50]:
np.arange(0.4,10.4,0.3)

array([ 0.4,  0.7,  1. ,  1.3,  1.6,  1.9,  2.2,  2.5,  2.8,  3.1,  3.4,
        3.7,  4. ,  4.3,  4.6,  4.9,  5.2,  5.5,  5.8,  6.1,  6.4,  6.7,
        7. ,  7.3,  7.6,  7.9,  8.2,  8.5,  8.8,  9.1,  9.4,  9.7, 10. ,
       10.3])

In [53]:
list(np.arange(0.4,5.4,1))

[0.4, 1.4, 2.4, 3.3999999999999995, 4.3999999999999995]

In [57]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [59]:
np.linspace(1,5,10) #linespace takes stat stop and total elemnts to be generated so according to that it creates spacing in each element

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [62]:
np.logspace(1,5,7) #By default base 10

array([1.00000000e+01, 4.64158883e+01, 2.15443469e+02, 1.00000000e+03,
       4.64158883e+03, 2.15443469e+04, 1.00000000e+05])

In [63]:
np.logspace(1,5,7,base=10)

array([1.00000000e+01, 4.64158883e+01, 2.15443469e+02, 1.00000000e+03,
       4.64158883e+03, 2.15443469e+04, 1.00000000e+05])

In [64]:
np.logspace(1,5,7,base=2)

array([ 2.        ,  3.1748021 ,  5.0396842 ,  8.        , 12.69920842,
       20.1587368 , 32.        ])

In [71]:
np.zeros(5) #1d dataset with zeros

array([0., 0., 0., 0., 0.])

In [72]:
np.zeros((3,4)) #2d dataset with zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.zeros((3,4)).ndim

2

In [73]:
np.zeros((3,4,2)) #3d dataset with zeros

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [70]:
np.zeros((3,4,2)).ndim

3

In [74]:
np.zeros((3,4,2,3)) 

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [77]:
np.zeros((3,4,2,3)).ndim #4d dataset

4

In [79]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [80]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
arr=np.ones((3,4))

In [82]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [83]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [84]:
arr-2

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]])

In [87]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [92]:
np.eye(5) #5 cross 5 square matrix with one on diagonal and zero elesewhere

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [93]:
import pandas as pd

In [94]:
arr=np.eye(5)

In [95]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
df=pd.DataFrame(arr)

In [97]:
df

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [98]:
srs=pd.Series(arr)

ValueError: Data must be 1-dimensional

In [99]:
#Therefore we can convert only 1d array to series as serie takes only one d data in pandas

In [100]:
#Therefore we can convert any numpy array to pandas dataframe

In [101]:
df

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [103]:
df.columns=["a","b","c","d","e"]

In [104]:
df

a    b    c    d    e
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [110]:
df.set_index(pd.Index(["appe","banana","cat","dog","elephant"]))

a    b    c    d    e
appe      1.0  0.0  0.0  0.0  0.0
banana    0.0  1.0  0.0  0.0  0.0
cat       0.0  0.0  1.0  0.0  0.0
dog       0.0  0.0  0.0  1.0  0.0
elephant  0.0  0.0  0.0  0.0  1.0

In [117]:
np.random.rand(2,5) #Gives random values between given two positional values

array([[0.84401747, 0.43841543, 0.07158184, 0.58358387, 0.93617799],
       [0.55068213, 0.01062319, 0.15504137, 0.44597466, 0.22594122]])

In [118]:
np.random.randn(2,5) #Gives random values depending on standard normal distribution where mean=0 and standard deviation =1

array([[-1.36355344, -0.42228356, -0.5624241 ,  0.13117167,  0.19227761],
       [ 0.00730856,  0.5825584 ,  1.05461263, -0.03371878,  1.68494417]])

In [120]:
np.random.randint(1,5,(3,4)) #gives 3 cross 4 matrix with random integers in range 1 and 5

array([[2, 2, 1, 4],
       [4, 4, 2, 2],
       [3, 1, 4, 4]])

In [122]:
np.asarray([1,3,6,7])

array([1, 3, 6, 7])

In [123]:
arr=np.random.randint(1,5,(3,4))

In [124]:
arr

array([[3, 2, 2, 1],
       [3, 1, 3, 1],
       [4, 4, 4, 4]])

In [125]:
arr.ndim

2

In [126]:
arr.size

12

In [127]:
arr.shape

(3, 4)

In [129]:
arr.reshape((2,6)) #so basically here dataset will not change only shape will be changed so 3*4=12 and 2*6=12 both should be same

array([[3, 2, 2, 1, 3, 1],
       [3, 1, 4, 4, 4, 4]])

In [131]:
arr.reshape((2,5))  #So this error will arise if 2*5!=12

ValueError: cannot reshape array of size 12 into shape (2,5)

In [133]:
arr.reshape((4,-1))

array([[3, 2, 2],
       [1, 3, 1],
       [3, 1, 4],
       [4, 4, 4]])

In [135]:
arr.reshape((4,-6378))

array([[3, 2, 2],
       [1, 3, 1],
       [3, 1, 4],
       [4, 4, 4]])

In [136]:
#We can give any negative number as second argument so it will just replace by correct number eg 4*(negative num) = 12. it will handle

In [138]:
arr.reshape(2,2,3)

array([[[3, 2, 2],
        [1, 3, 1]],

       [[3, 1, 4],
        [4, 4, 4]]])

In [139]:
arr.reshape(2,2,3,2)

ValueError: cannot reshape array of size 12 into shape (2,2,3,2)

In [141]:
arr.reshape(2,2,3,1,1)

array([[[[[3]],

         [[2]],

         [[2]]],


        [[[1]],

         [[3]],

         [[1]]]],



       [[[[3]],

         [[1]],

         [[4]]],


        [[[4]],

         [[4]],

         [[4]]]]])

In [142]:
arr1=np.random.randint(1,10,(5,6))

In [143]:
arr1

array([[4, 1, 7, 3, 5, 2],
       [2, 5, 8, 8, 3, 5],
       [3, 5, 3, 1, 9, 3],
       [1, 4, 5, 5, 1, 2],
       [3, 6, 9, 2, 6, 9]])

In [145]:
arr2=(arr1>5)

In [146]:
arr2

array([[False, False,  True, False, False, False],
       [False, False,  True,  True, False, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [False,  True,  True, False,  True,  True]])

In [147]:
arr2.dtype

dtype('bool')

In [150]:
arr2[arr1>5]

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [151]:
arr1[arr1>5]

array([7, 8, 8, 9, 6, 9, 6, 9])

In [152]:
arr3=arr1[arr1>5]

In [153]:
arr3

array([7, 8, 8, 9, 6, 9, 6, 9])

In [154]:
arr1

array([[4, 1, 7, 3, 5, 2],
       [2, 5, 8, 8, 3, 5],
       [3, 5, 3, 1, 9, 3],
       [1, 4, 5, 5, 1, 2],
       [3, 6, 9, 2, 6, 9]])

In [155]:
arr1[1]

array([2, 5, 8, 8, 3, 5])

In [156]:
arr1[1,2]

8

In [158]:
arr1[0]

array([4, 1, 7, 3, 5, 2])

In [162]:
arr1[0,0:2]

array([4, 1])

In [163]:
arr1[2:4,2:4]

array([[3, 1],
       [5, 5]])

In [170]:
arr1= np.random.randint(1,3,(3,3))
arr2= np.random.randint(1,3,(3,3))

In [171]:
arr1

array([[1, 2, 1],
       [2, 2, 2],
       [1, 2, 1]])

In [172]:
arr2

array([[2, 1, 1],
       [2, 1, 2],
       [2, 2, 1]])

In [175]:
arr1+arr2

array([[3, 3, 2],
       [4, 3, 4],
       [3, 4, 2]])

In [176]:
arr1-arr2

array([[-1,  1,  0],
       [ 0,  1,  0],
       [-1,  0,  0]])

In [177]:
arr1*arr2

array([[2, 2, 1],
       [4, 2, 4],
       [2, 4, 1]])

In [178]:
#Therefore here all operations are performed indexwise

In [188]:
arr1=[[2,2,1],[1,1,1,],[1,2,2]]

In [189]:
arr2=[[1,2,2],[1,2,1],[2,1,1]]

In [190]:
arr1

[[2, 2, 1], [1, 1, 1], [1, 2, 2]]

In [191]:
arr2

[[1, 2, 2], [1, 2, 1], [2, 1, 1]]

In [193]:
arr1=np.matrix(arr1)

In [194]:
arr2=np.matrix(arr2)

In [195]:
arr1

matrix([[2, 2, 1],
        [1, 1, 1],
        [1, 2, 2]])

In [196]:
arr2

matrix([[1, 2, 2],
        [1, 2, 1],
        [2, 1, 1]])

In [197]:
arr1*arr2

matrix([[6, 9, 7],
        [4, 5, 4],
        [7, 8, 6]])

In [198]:
arr1/arr2

matrix([[2. , 1. , 0.5],
        [1. , 0.5, 1. ],
        [0.5, 2. , 2. ]])

In [199]:
arr1/0

/tmp/ipykernel_312/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


matrix([[inf, inf, inf],
        [inf, inf, inf],
        [inf, inf, inf]])

In [200]:
#Numpy - Broadcasting

In [201]:
arr=np.zeros((3,4))

In [202]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [203]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [204]:
arr*3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [211]:
a=np.array([1,2,3,4])

In [206]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [207]:
a

array([1, 2, 3, 4])

In [213]:
arr+a #Column wise addition 

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [222]:
b=np.array([[1,2,3]])

In [216]:
arr+b #Can't bradcast as 4 columns in arr and ony 3 elemnts in b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [224]:
arr+b.T #Row wise addition 

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [226]:
b.T #Initially b was (3,0) now it is (0,3)

array([[1],
       [2],
       [3]])

In [228]:
arr= arr+b.T

In [229]:
arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [231]:
np.sqrt(arr)

array([[1.        , 1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081]])

In [233]:
np.log(arr)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.69314718, 0.69314718, 0.69314718, 0.69314718],
       [1.09861229, 1.09861229, 1.09861229, 1.09861229]])

In [234]:
np.exp(arr)

array([[ 2.71828183,  2.71828183,  2.71828183,  2.71828183],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ,  7.3890561 ],
       [20.08553692, 20.08553692, 20.08553692, 20.08553692]])

In [235]:
np.max(arr)

3.0

In [236]:
np.mean(arr)

2.0

In [237]:
np.std(arr)

0.816496580927726